/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#131313',
        surface: '#131313',
        'on-tertiary-fixed-variant': '#891e00',
        'surface-container-highest': '#353534',
        background: '#131313',
        'inverse-surface': '#e5e2e1',
        outline: '#8d90a2',
        'inverse-primary': '#004ced',
        'surface-container': '#201f1f',
        primary: '#b7c4ff',
        'on-secondary-fixed-variant': '#673d00',
        'on-secondary-container': '#653c00',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed': '#2b1700',
        'inverse-on-surface': '#313030',
        'tertiary-fixed': '#ffdbd2',
        'on-secondary': '#482900',
        'on-primary': '#002682',
        error: '#ffb4ab',
        'surface-bright': '#3a3939',
        'secondary-fixed-dim': '#ffb866',
        'surface-tint': '#b7c4ff',
        'on-tertiary-fixed': '#3c0800',
        'surface-variant': '#353534',
        'on-primary-fixed': '#001452',
        'on-error': '#690005',
        'on-background': '#e5e2e1',
        'outline-variant': '#434656',
        'tertiary-fixed-dim': '#ffb4a1',
        'tertiary-container': '#bf3003',
        'surface-container-high': '#2a2a2a',
        'on-tertiary': '#611300',
        'secondary-container': '#fd9e00',
        'on-primary-container': '#dfe3ff',
        'surface-container-low': '#1c1b1b',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed-variant': '#0038b6',
        'error-container': '#93000a',
        secondary: '#ffc482',
        'secondary-fixed': '#ffddba',
        'on-surface-variant': '#c3c5d9',
        'on-error-container': '#ffdad6',
        'primary-container': '#0052ff',
        tertiary: '#ffb4a1',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-container': '#ffddd5',
        orange: '#FF9F00',
      },
      borderRadius: {
        DEFAULT: '0',
        none: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      spacing: {
        gutter: '24px',
        'section-gap': '120px',
        'grid-pattern-size': '40px',
        'container-padding': '64px',
        unit: '8px',
      },
      fontFamily: {
        'label-mono': ['Space Grotesk', 'monospace'],
        'headline-italic': ['Newsreader', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'label-mono': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-italic': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
