/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#0d0d0d',
        'surface-dim': '#080808',
        'surface-bright': '#1a1a1a',
        'surface-container': '#151515',
        'surface-container-low': '#0a0a0a',
        'surface-container-high': '#1e1e1e',
        'surface-container-lowest': '#000000',
        'surface-container-highest': '#2a2a2a',
        'surface-variant': '#252525',
        background: '#000000',
        'on-background': '#ececec',
        'on-surface': '#ececec',
        'on-surface-variant': '#949494',
        primary: '#b7c4ff',
        'on-primary': '#001a6e',
        'primary-container': '#004cff',
        'on-primary-container': '#dfe3ff',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001452',
        'on-primary-fixed-variant': '#0038b6',
        'inverse-primary': '#004ced',
        'surface-tint': '#b7c4ff',
        accent: '#FF9F00',
        'accent-container': '#FF9F00',
        'on-accent': '#1a0f00',
        'accent-dim': '#cc7f00',
        secondary: '#FF9F00',
        'secondary-container': '#FF9F00',
        'on-secondary': '#1a0f00',
        'on-secondary-container': '#1a0f00',
        'on-secondary-fixed': '#1a0f00',
        'on-secondary-fixed-variant': '#1a0f00',
        'secondary-fixed': '#FF9F00',
        'secondary-fixed-dim': '#cc7f00',
        orange: '#FF9F00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#444466',
        'outline-variant': '#2e2e4a',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
      },
      borderRadius: {
        DEFAULT: '0',
        none: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      spacing: {
        gutter: '24px',
        'section-gap': '120px',
        'grid-pattern-size': '40px',
        'container-padding': '64px',
        unit: '8px',
      },
      fontFamily: {
        'label-mono': ['Space Grotesk', 'monospace'],
        'headline-italic': ['Newsreader', 'serif'],
        'body-md': ['Geist Sans', 'Inter', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'body-lg': ['Geist Sans', 'Inter', 'sans-serif'],
        'headline-xl': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
      },
      fontSize: {
        'label-mono': ['12px', { lineHeight: '1.0', letterSpacing: '0.12em', fontWeight: '500' }],
        'headline-italic': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['clamp(2.5rem, 5vw, 72px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['clamp(1.75rem, 3.5vw, 48px)', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['clamp(1.25rem, 2.5vw, 32px)', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
