/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#0f0f0f',
        'surface-dim': '#080808',
        'surface-bright': '#1c1c1c',
        'surface-container': '#161616',
        'surface-container-low': '#0a0a0a',
        'surface-container-high': '#1f1f1f',
        'surface-container-lowest': '#000000',
        'surface-container-highest': '#2b2b2b',
        'surface-variant': '#262626',
        background: '#000000',
        'on-background': '#eeeeee',
        'on-surface': '#eeeeee',
        'on-surface-variant': '#999999',
        primary: '#3b82f6',
        'on-primary': '#0a1628',
        'primary-container': '#1d4ed8',
        'on-primary-container': '#dbeafe',
        'primary-fixed': '#dbeafe',
        'primary-fixed-dim': '#93c5fd',
        'on-primary-fixed': '#0a1628',
        'on-primary-fixed-variant': '#1d4ed8',
        'inverse-primary': '#1d4ed8',
        'surface-tint': '#3b82f6',
        accent: '#FF9F00',
        'accent-container': '#FF9F00',
        'on-accent': '#140a00',
        'accent-dim': '#d48900',
        secondary: '#FF9F00',
        'secondary-container': '#FF9F00',
        'on-secondary': '#140a00',
        'on-secondary-container': '#140a00',
        'on-secondary-fixed': '#140a00',
        'on-secondary-fixed-variant': '#140a00',
        'secondary-fixed': '#FF9F00',
        'secondary-fixed-dim': '#d48900',
        orange: '#FF9F00',
        error: '#ef4444',
        'on-error': '#fee2e2',
        'error-container': '#991b1b',
        'on-error-container': '#fee2e2',
        outline: '#3b3b52',
        'outline-variant': '#2a2a40',
        'inverse-surface': '#eeeeee',
        'inverse-on-surface': '#222222',
      },
      borderRadius: {
        DEFAULT: '0',
        none: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      spacing: {
        gutter: '24px',
        'section-gap': '120px',
        'grid-pattern-size': '40px',
        'container-padding': '64px',
        unit: '8px',
      },
      fontFamily: {
        'label-mono': ['Space Grotesk', 'monospace'],
        'headline-italic': ['Newsreader', 'serif'],
        'body-md': ['Geist Sans', 'Inter', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'body-lg': ['Geist Sans', 'Inter', 'sans-serif'],
        'headline-xl': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
      },
      fontSize: {
        'label-mono': ['12px', { lineHeight: '1.0', letterSpacing: '0.12em', fontWeight: '500' }],
        'headline-italic': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['clamp(2.5rem, 5vw, 72px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['clamp(1.75rem, 3.5vw, 48px)', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['clamp(1.25rem, 2.5vw, 32px)', { lineHeight: '1.3', fontWeight: '600' }],
      },
      keyframes: {
        'marquee-smooth': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee-smooth 40s linear infinite',
      },
    },
  },
  plugins: [],
};